services:
  custom-cores-windows:
    image: ${IMAGE_TAG:-renode-custom-cores:offline-windows}
    build:
      context: .
      dockerfile: Dockerfile.windows
    platform: ${DOCKER_PLATFORM:-windows/amd64}
    network_mode: none
    working_dir: C:\workspace
    environment:
      RENODE_BUILD_HOST_ARCH: ${RENODE_BUILD_HOST_ARCH:-}
      RENODE_CUSTOM_CORE_ARCHES: ${RENODE_CUSTOM_CORE_ARCHES:-}
    volumes:
      - ../..:C:\workspace
